apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sleeper3
  name: sleeper3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sleeper3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleeper3
    spec:
      containers:
      - image: njwgroeneveld/sleeper:v1.0
        name: sleeper
        resources: {}
status: {}
